#!/bin/sh
tr -d " " |
sed "s/|[^=]*=/,/g" |
gawk -F "," '{
if ($2 != "")
{
  printf "%s\tpo:no\n", $2;
  if ($3 != $2 && $3 != "" && $3 != "-" && !match($3, "/")) printf "%s\tst:%s po:no\n", $3, $2;
  if ($4 != $2 && $4 != "" && $4 != "-" && !match($4, "/")) printf "%s\tst:%s po:no\n", $4, $2;
  if ($5 != $2 && $5 != "" && $5 != "-" && !match($5, "/")) printf "%s\tst:%s po:no\n", $5, $2;
  if ($6 != $2 && $6 != "" && $6 != "-" && !match($6, "/")) printf "%s\tst:%s po:no\n", $6, $2;
  if ($7 != $2 && $7 != "" && $7 != "-" && !match($7, "/")) printf "%s\tst:%s po:no\n", $7, $2;
  if ($8 != $2 && $8 != "" && $8 != "-" && !match($8, "/")) printf "%s\tst:%s po:no\n", $8, $2;
  if ($9 != $2 && $9 != "" && $9 != "-" && !match($9, "/")) printf "%s\tst:%s po:no\n", $9, $2;
  if ($10 != $2 && $10 != "" && $10 != "-" && !match($10, "/")) printf "%s\tst:%s po:no\n", $10, $2;
  if ($11 != $2 && $11 != "" && $11 != "-" && !match($11, "/")) printf "%s\tst:%s po:no\n", $11, $2;
  if ($12 != $2 && $12 != "" && $12 != "-" && !match($12, "/")) printf "%s\tst:%s po:no\n", $12, $2;
  if ($13 != $2 && $13 != "" && $13 != "-" && !match($13, "/")) printf "%s\tst:%s po:no\n", $13, $2;
  if ($14 != $2 && $14 != "" && $14 != "-" && !match($14, "/")) printf "%s\tst:%s po:no\n", $14, $2;
  if ($15 != $2 && $15 != "" && $15 != "-" && !match($15, "/")) printf "%s\tst:%s po:no\n", $15, $2;
  if ($16 != $2 && $16 != "" && $16 != "-" && !match($16, "/")) printf "%s\tst:%s po:no\n", $16, $2;
  if ($17 != $2 && $17 != "" && $17 != "-" && !match($17, "/")) printf "%s\tst:%s po:no\n", $17, $2;
}
}'

